# Generated by Django 4.1.1 on 2022-11-04 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=30, verbose_name='event operation')),
                ('from_table', models.CharField(max_length=30, verbose_name='event table')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='event date')),
                ('details', models.TextField(default=None, verbose_name='event details')),
            ],
            options={
                'db_table': 'logs',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, verbose_name='student id')),
                ('name', models.CharField(max_length=20, verbose_name='student name')),
                ('login', models.CharField(max_length=5, verbose_name='student login')),
                ('password', models.CharField(max_length=20, verbose_name='student password')),
                ('level', models.IntegerField(default=1, verbose_name='student lvl')),
                ('mana_earned', models.IntegerField(default=0, verbose_name='mana earned by student')),
                ('last_homework_id', models.IntegerField(default=1, verbose_name='last homework id')),
                ('last_classwork_id', models.IntegerField(default=1, verbose_name='last classwork id')),
                ('is_admin', models.BooleanField(default=0, verbose_name='is this account is admin')),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='theme name')),
                ('type', models.IntegerField(verbose_name='theme type')),
            ],
            options={
                'db_table': 'themes',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='work name')),
                ('grades', models.CharField(max_length=100, verbose_name='work grades')),
                ('max_score', models.FloatField(verbose_name='max score')),
                ('exercises', models.IntegerField(verbose_name='amount of exercises')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.theme')),
            ],
            options={
                'db_table': 'works',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mana', models.IntegerField(default=0, verbose_name='mana')),
                ('score', models.FloatField(default=0, verbose_name='score')),
                ('max_score', models.FloatField(default=0, verbose_name='max_score')),
                ('grades', models.CharField(default=None, max_length=200, verbose_name='grades string')),
                ('exercises', models.IntegerField(verbose_name='amount of exercises(current student)')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.student')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.work')),
            ],
            options={
                'db_table': 'grades',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.IntegerField(verbose_name='admin permissions')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.student')),
            ],
            options={
                'db_table': 'admins',
            },
        ),
    ]
